sudo: required
services:
  - docker

before_install:
  - docker build -t tundemulti/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tundemulti/react-test npm test -- --coverage

after_success:
  - docker build -t tundemulti/multi-client ./client
  - docker build -t tundemulti/multi-server ./server
  - docker build -t tundemulti/multi-nginx ./nginx
  - docker build -t tundemulti/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tundemulti/multi-client
  - docker push tundemulti/multi-server
  - docker push tundemulti/multi-nginx
  - docker push tundemulti/multi-worker